
-- --------------------------------------------------------

--
-- Structure de la table `vj9e_badge_lang`
--

CREATE TABLE `vj9e_badge_lang` (
  `id_badge` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `name` varchar(64) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `group_name` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `vj9e_badge_lang`
--

INSERT INTO `vj9e_badge_lang` (`id_badge`, `id_lang`, `name`, `description`, `group_name`) VALUES
(21, 1, 'Shopgate installé', '', ''),
(21, 2, 'Shopgate installed', 'You have installed the Shopgate module', 'Partners'),
(22, 1, 'Shopgate configuré', '', ''),
(22, 2, 'Shopgate configured', 'You have configured the Shopgate module', 'Partners'),
(23, 1, 'Shopgate actif', '', ''),
(23, 2, 'Shopgate active', 'Your Shopgate module is active', 'Partners'),
(24, 1, 'Shopgate très actif', '', ''),
(24, 2, 'Shopgate very active', 'Your Shopgate module is very active', 'Partners'),
(25, 1, 'Skrill installé', '', ''),
(25, 2, 'Skrill installed', 'You have installed the Skrill module', 'Partners'),
(26, 1, 'Skrill configuré', '', ''),
(26, 2, 'Skrill configured', 'You have configured the Skrill module', 'Partners'),
(27, 1, 'Skrill actif', '', ''),
(27, 2, 'Skrill active', 'Your Skrill module is active', 'Partners'),
(28, 1, 'Skrill très actif', '', ''),
(28, 2, 'Skrill very active', 'Your Skrill module is very active', 'Partners'),
(53, 1, 'Shopping Flux installé', '', ''),
(53, 2, 'Shopping Feed installed', 'You have installed the Shopping Feed module', 'Partners'),
(54, 1, 'Shopping Flux configuré', '', ''),
(54, 2, 'Shopping Feed configured', 'You have configured the Shopping Feed module', 'Partners'),
(81, 1, 'Authorize Aim installé', '', ''),
(81, 2, 'Authorize Aim installed', 'You have installed the Authorize Aim module', 'Partners'),
(82, 1, 'Authorize Aim configuré', '', ''),
(82, 2, 'Authorize Aim configured', 'You have configured the Authorize Aim module', 'Partners'),
(83, 1, 'Authorize Aim actif', '', ''),
(83, 2, 'Authorize Aim active', 'Your Authorize Aim module is active', 'Partners'),
(84, 1, 'Authorize Aim très actif', '', ''),
(84, 2, 'Authorize Aim very active', 'Your Authorize Aim module is very active', 'Partners'),
(85, 1, 'Ebay installé', '', ''),
(85, 2, 'Ebay installed', 'You have installed the Ebay module', 'Partners'),
(86, 1, 'Ebay configuré', '', ''),
(86, 2, 'Ebay configured', 'You have configured the Ebay module', 'Partners'),
(87, 1, 'Ebay actif', '', ''),
(87, 2, 'Ebay active', 'Your Ebay module is active', 'Partners'),
(88, 1, 'Ebay très actif', '', ''),
(88, 2, 'Ebay very active', 'Your Ebay module is very active', 'Partners'),
(89, 1, 'PayPlug installé', '', ''),
(89, 2, 'PayPlug installed', 'You have installed the PayPlug module', 'Partners'),
(90, 1, 'PayPlug configuré', '', ''),
(90, 2, 'PayPlug configured', 'You have configured the PayPlug module', 'Partners'),
(91, 1, 'PayPlug actif', '', ''),
(91, 2, 'PayPlug active', 'Your PayPlug module is active', 'Partners'),
(92, 1, 'PayPlug très actif', '', ''),
(92, 2, 'PayPlug very active', 'Your PayPlug module is very active', 'Partners'),
(93, 1, 'Affinity Items installé', '', ''),
(93, 2, 'Affinity Items installed', 'You have installed the Affinity Items module', 'Partners'),
(94, 1, 'Affinity Items configuré', '', ''),
(94, 2, 'Affinity Items configured', 'You have configured the Affinity Items module', 'Partners'),
(95, 1, 'DPD Poland installé', '', ''),
(95, 2, 'DPD Poland installed', 'You have installed the DPD Poland module', 'Partners'),
(96, 1, 'DPD Poland configuré', '', ''),
(96, 2, 'DPD Poland configured', 'You have configured the DPD Poland module', 'Partners'),
(97, 1, 'DPD Poland actif', '', ''),
(97, 2, 'DPD Poland active', 'Your DPD Poland module is active', 'Partners'),
(98, 1, 'DPD Poland très actif', '', ''),
(98, 2, 'DPD Poland very active', 'Your DPD Poland module is very active', 'Partners'),
(99, 1, 'Envoimoinscher installé', '', ''),
(99, 2, 'Envoimoinscher installed', 'You have installed the Envoimoinscher module', 'Partners'),
(100, 1, 'Envoimoinscher configuré', '', ''),
(100, 2, 'Envoimoinscher configured', 'You have configured the Envoimoinscher module', 'Partners'),
(101, 1, 'Envoimoinscher actif', '', ''),
(101, 2, 'Envoimoinscher active', 'Your Envoimoinscher module is active', 'Partners'),
(102, 1, 'Envoimoinscher très actif', '', ''),
(102, 2, 'Envoimoinscher very active', 'Your Envoimoinscher module is very active', 'Partners'),
(103, 1, 'Klik&Pay installé', '', ''),
(103, 2, 'Klik&Pay installed', 'You have installed the Klik&Pay module', 'Partners'),
(104, 1, 'Klik&Pay configuré', '', ''),
(104, 2, 'Klik&Pay configured', 'You have configured the Klik&Pay module', 'Partners'),
(105, 1, 'Klik&Pay actif', '', ''),
(105, 2, 'Klik&Pay active', 'Your Klik&Pay module is active', 'Partners'),
(106, 1, 'Klik&Pay très actif', '', ''),
(106, 2, 'Klik&Pay very active', 'Your Klik&Pay module is very active', 'Partners'),
(107, 1, 'Clickline installé', '', ''),
(107, 2, 'Clickline installed', 'You have installed the Clickline module', 'Partners'),
(108, 1, 'Clickline configuré', '', ''),
(108, 2, 'Clickline configured', 'You have configured the Clickline module', 'Partners'),
(109, 1, 'Clickline actif', '', ''),
(109, 2, 'Clickline active', 'Your Clickline module is active', 'Partners'),
(110, 1, 'Clickline très actif', '', ''),
(110, 2, 'Clickline very active', 'Your Clickline module is very active', 'Partners'),
(111, 1, 'CDiscount installé', '', ''),
(111, 2, 'CDiscount installed', 'You have installed the CDiscount module', 'Partners'),
(112, 1, 'CDiscount configuré', '', ''),
(112, 2, 'CDiscount configured', 'You have configured the CDiscount module', 'Partners'),
(113, 1, 'CDiscount actif', '', ''),
(113, 2, 'CDiscount active', 'Your CDiscount module is active', 'Partners'),
(114, 1, 'CDiscount très actif', '', ''),
(114, 2, 'CDiscount very active', 'Your CDiscount module is very active', 'Partners'),
(115, 1, 'illicoPresta installé', '', ''),
(115, 2, 'illicoPresta installed', 'You have installed the illicoPresta module', 'Partners'),
(116, 1, 'illicoPresta configuré', '', ''),
(116, 2, 'illicoPresta configured', 'You have configured the illicoPresta module', 'Partners'),
(117, 1, 'illicoPresta actif', '', ''),
(117, 2, 'illicoPresta active', 'Your illicoPresta module is active', 'Partners'),
(118, 1, 'illicoPresta très actif', '', ''),
(118, 2, 'illicoPresta very active', 'Your illicoPresta module is very active', 'Partners'),
(119, 1, 'NetReviews installé', '', ''),
(119, 2, 'NetReviews installed', 'You have installed the NetReviews module', 'Partners'),
(120, 1, 'NetReviews configuré', '', ''),
(120, 2, 'NetReviews configured', 'You have configured the NetReviews module', 'Partners'),
(121, 1, 'NetReviews actif', '', ''),
(121, 2, 'NetReviews active', 'Your NetReviews module is active', 'Partners'),
(122, 1, 'NetReviews très actif', '', ''),
(122, 2, 'NetReviews very active', 'Your NetReviews module is very active', 'Partners'),
(123, 1, 'Bluesnap installé', '', ''),
(123, 2, 'Bluesnap installed', 'You have installed the Bluesnap module', 'Partners'),
(124, 1, 'Bluesnap configuré', '', ''),
(124, 2, 'Bluesnap configured', 'You have configured the Bluesnap module', 'Partners'),
(125, 1, 'Bluesnap actif', '', ''),
(125, 2, 'Bluesnap active', 'Your Bluesnap module is active', 'Partners'),
(126, 1, 'Bluesnap très actif', '', ''),
(126, 2, 'Bluesnap very active', 'Your Bluesnap module is very active', 'Partners'),
(127, 1, 'Desjardins installé', '', ''),
(127, 2, 'Desjardins installed', 'You have installed the Desjardins module', 'Partners'),
(128, 1, 'Desjardins configuré', '', ''),
(128, 2, 'Desjardins configured', 'You have configured the Desjardins module', 'Partners'),
(129, 1, 'Desjardins actif', '', ''),
(129, 2, 'Desjardins active', 'Your Desjardins module is active', 'Partners'),
(130, 1, 'Desjardins très actif', '', ''),
(130, 2, 'Desjardins very active', 'Your Desjardins module is very active', 'Partners'),
(131, 1, 'First Data installé', '', ''),
(131, 2, 'First Data installed', 'You have installed the First Data module', 'Partners'),
(132, 1, 'First Data configuré', '', ''),
(132, 2, 'First Data configured', 'You have configured the First Data module', 'Partners'),
(133, 1, 'First Data actif', '', ''),
(133, 2, 'First Data active', 'Your First Data module is active', 'Partners'),
(134, 1, 'First Data très actif', '', ''),
(134, 2, 'First Data very active', 'Your First Data module is very active', 'Partners'),
(135, 1, 'Give.it installé', '', ''),
(135, 2, 'Give.it installed', 'You have installed the Give.it module', 'Partners'),
(136, 1, 'Give.it configuré', '', ''),
(136, 2, 'Give.it configured', 'You have configured the Give.it module', 'Partners'),
(137, 1, 'Give.it actif', '', ''),
(137, 2, 'Give.it active', 'Your Give.it module is active', 'Partners'),
(138, 1, 'Give.it très actif', '', ''),
(138, 2, 'Give.it very active', 'Your Give.it module is very active', 'Partners'),
(139, 1, 'Google Analytics installé', '', ''),
(139, 2, 'Google Analytics installed', 'You have installed the Google Analytics module', 'Partners'),
(140, 1, 'Google Analytics configuré', '', ''),
(140, 2, 'Google Analytics configured', 'You have configured the Google Analytics module', 'Partners'),
(141, 1, 'Google Analytics actif', '', ''),
(141, 2, 'Google Analytics active', 'Your Google Analytics module is active', 'Partners'),
(142, 1, 'Google Analytics très actif', '', ''),
(142, 2, 'Google Analytics very active', 'Your Google Analytics module is very active', 'Partners'),
(143, 1, 'PagSeguro installé', '', ''),
(143, 2, 'PagSeguro installed', 'You have installed the PagSeguro module', 'Partners'),
(144, 1, 'PagSeguro configuré', '', ''),
(144, 2, 'PagSeguro configured', 'You have configured the PagSeguro module', 'Partners'),
(145, 1, 'PagSeguro actif', '', ''),
(145, 2, 'PagSeguro active', 'Your PagSeguro module is active', 'Partners'),
(146, 1, 'PagSeguro très actif', '', ''),
(146, 2, 'PagSeguro very active', 'Your PagSeguro module is very active', 'Partners'),
(147, 1, 'Paypal MX installé', '', ''),
(147, 2, 'Paypal MX installed', 'You have installed the Paypal MX module', 'Partners'),
(148, 1, 'Paypal MX configuré', '', ''),
(148, 2, 'Paypal MX configured', 'You have configured the Paypal MX module', 'Partners'),
(149, 1, 'Paypal MX actif', '', ''),
(149, 2, 'Paypal MX active', 'Your Paypal MX module is active', 'Partners'),
(150, 1, 'Paypal MX très actif', '', ''),
(150, 2, 'Paypal MX very active', 'Your Paypal MX module is very active', 'Partners'),
(151, 1, 'Paypal USA installé', '', ''),
(151, 2, 'Paypal USA installed', 'You have installed the Paypal USA module', 'Partners'),
(152, 1, 'Paypal USA configuré', '', ''),
(152, 2, 'Paypal USA configured', 'You have configured the Paypal USA module', 'Partners'),
(153, 1, 'Paypal USA actif', '', ''),
(153, 2, 'Paypal USA active', 'Your Paypal USA module is active', 'Partners'),
(154, 1, 'Paypal USA très actif', '', ''),
(154, 2, 'Paypal USA very active', 'Your Paypal USA module is very active', 'Partners'),
(155, 1, 'PayULatam installé', '', ''),
(155, 2, 'PayULatam installed', 'You have installed the PayULatam module', 'Partners'),
(156, 1, 'PayULatam configuré', '', ''),
(156, 2, 'PayULatam configured', 'You have configured the PayULatam module', 'Partners'),
(157, 1, 'PayULatam actif', '', ''),
(157, 2, 'PayULatam active', 'Your PayULatam module is active', 'Partners'),
(158, 1, 'PayULatam très actif', '', ''),
(158, 2, 'PayULatam very active', 'Your PayULatam module is very active', 'Partners'),
(159, 1, 'PrestaStats installé', '', ''),
(159, 2, 'PrestaStats installed', 'You have installed the PrestaStats module', 'Partners'),
(160, 1, 'PrestaStats configuré', '', ''),
(160, 2, 'PrestaStats configured', 'You have configured the PrestaStats module', 'Partners'),
(161, 1, 'PrestaStats actif', '', ''),
(161, 2, 'PrestaStats active', 'Your PrestaStats module is active', 'Partners'),
(162, 1, 'PrestaStats très actif', '', ''),
(162, 2, 'PrestaStats very active', 'Your PrestaStats module is very active', 'Partners'),
(163, 1, 'Riskified installé', '', ''),
(163, 2, 'Riskified installed', 'You have installed the Riskified module', 'Partners'),
(164, 1, 'Riskified configuré', '', ''),
(164, 2, 'Riskified configured', 'You have configured the Riskified module', 'Partners'),
(165, 1, 'Riskified actif', '', ''),
(165, 2, 'Riskified active', 'Your Riskified module is active', 'Partners'),
(166, 1, 'Riskified très actif', '', ''),
(166, 2, 'Riskified very active', 'Your Riskified module is very active', 'Partners'),
(167, 1, 'Simplify installé', '', ''),
(167, 2, 'Simplify installed', 'You have installed the Simplify module', 'Partners'),
(168, 1, 'Simplify configuré', '', ''),
(168, 2, 'Simplify configured', 'You have configured the Simplify module', 'Partners'),
(169, 1, 'Simplify actif', '', ''),
(169, 2, 'Simplify active', 'Your Simplify module is active', 'Partners'),
(170, 1, 'Simplify très actif', '', ''),
(170, 2, 'Simplify very active', 'Your Simplify module is very active', 'Partners'),
(171, 1, 'VTPayment installé', '', ''),
(171, 2, 'VTPayment installed', 'You have installed the VTPayment module', 'Partners'),
(172, 1, 'VTPayment configuré', '', ''),
(172, 2, 'VTPayment configured', 'You have configured the VTPayment module', 'Partners'),
(173, 1, 'VTPayment actif', '', ''),
(173, 2, 'VTPayment active', 'Your VTPayment module is active', 'Partners'),
(174, 1, 'VTPayment très actif', '', ''),
(174, 2, 'VTPayment very active', 'Your VTPayment module is very active', 'Partners'),
(175, 1, 'Yotpo installé', '', ''),
(175, 2, 'Yotpo installed', 'You have installed the Yotpo module', 'Partners'),
(176, 1, 'Yotpo configuré', '', ''),
(176, 2, 'Yotpo configured', 'You have configured the Yotpo module', 'Partners'),
(177, 1, 'Yotpo actif', '', ''),
(177, 2, 'Yotpo active', 'Your Yotpo module is active', 'Partners'),
(178, 1, 'Yotpo très actif', '', ''),
(178, 2, 'Yotpo very active', 'Your Yotpo module is very active', 'Partners'),
(179, 1, 'Youstice installé', '', ''),
(179, 2, 'Youstice installed', 'You have installed the Youstice module', 'Partners'),
(180, 1, 'Youstice configuré', '', ''),
(180, 2, 'Youstice configured', 'You have configured the Youstice module', 'Partners'),
(181, 1, 'Youstice actif', '', ''),
(181, 2, 'Youstice active', 'Your Youstice module is active', 'Partners'),
(182, 1, 'Youstice très actif', '', ''),
(182, 2, 'Youstice very active', 'Your Youstice module is very active', 'Partners'),
(183, 1, 'Loyalty Lion installé', '', ''),
(183, 2, 'Loyalty Lion installed', 'You have installed the Loyalty Lion module', 'Partners'),
(184, 1, 'Loyalty Lion configuré', '', ''),
(184, 2, 'Loyalty Lion configured', 'You have configured the Loyalty Lion module', 'Partners'),
(185, 1, 'Loyalty Lion actif', '', ''),
(185, 2, 'Loyalty Lion active', 'Your Loyalty Lion module is active', 'Partners'),
(186, 1, 'Loyalty Lion très actif', '', ''),
(186, 2, 'Loyalty Lion very active', 'Your Loyalty Lion module is very active', 'Partners'),
(187, 1, 'Référencement', '', ''),
(187, 2, 'SEO', 'You enabled the URL rewriting through the tab \"Preferences > SEO and URLs\".', 'SEO'),
(188, 1, 'Performances', '', ''),
(188, 2, 'Site Performance', 'You enabled CCC (Combine, Compress and Cache), Rijndael and Smarty through the tab \r\nAdvanced Parameters > Performance.', 'Site Performance'),
(189, 1, 'Performances', '', ''),
(189, 2, 'Site Performance', 'You enabled media servers through the tab \"Advanced parameters > Performance\".', 'Site Performance'),
(190, 1, 'Moyens de paiement', '', ''),
(190, 2, 'Payment', 'You configured a payment solution on your shop.', 'Payment'),
(191, 1, 'Moyens de paiement', '', ''),
(191, 2, 'Payment', 'You offer two different payment methods to your customers.', 'Payment'),
(192, 1, 'Solutions de transport', '', ''),
(192, 2, 'Shipping', 'You configured a carrier on your shop.', 'Shipping'),
(193, 1, 'Solutions de transport', '', ''),
(193, 2, 'Shipping', 'You offer two shipping solutions (carriers) to your customers.', 'Shipping'),
(194, 1, 'Taille de catalogue', '', ''),
(194, 2, 'Catalog Size', 'You added your first product to your catalog!', 'Catalog Size'),
(195, 1, 'Taille de catalogue', '', ''),
(195, 2, 'Catalog Size', 'You have 10 products within your catalog.', 'Catalog Size'),
(196, 1, 'Points de contact', '', ''),
(196, 2, 'Contact information', 'You configured your phone number so your customers can reach you!', 'Contact information'),
(197, 1, 'Points de contact', '', ''),
(197, 2, 'Contact information', 'You added a third email address to your contact form.', 'Contact information'),
(198, 1, 'Points de contact', '', ''),
(198, 2, 'Contact information', 'You suggest a total of 5 departments to be reached by your customers via your contact form.', 'Contact information'),
(199, 1, 'Taille de catalogue', '', ''),
(199, 2, 'Catalog Size', 'You have 100 products within your catalog.', 'Catalog Size'),
(200, 1, 'Taille de catalogue', '', ''),
(200, 2, 'Catalog Size', 'You have 1,000 products within your catalog.', 'Catalog Size'),
(201, 1, 'Taille de catalogue', '', ''),
(201, 2, 'Catalog Size', 'You have 10,000 products within your catalog.', 'Catalog Size'),
(202, 1, 'Taille de catalogue', '', ''),
(202, 2, 'Catalog Size', 'You have 100,000 products within your catalog.', 'Catalog Size'),
(203, 1, 'Expérience', '', ''),
(203, 2, 'Days of Experience', 'You just installed PrestaShop!', 'Days of Experience'),
(204, 1, 'Expérience', '', ''),
(204, 2, 'Days of Experience', 'You installed PrestaShop a week ago!', 'Days of Experience'),
(205, 1, 'Personnalisation', '', ''),
(205, 2, 'Customization', 'You uploaded your own logo.', 'Customization'),
(206, 1, 'Personnalisation', '', ''),
(206, 2, 'Customization', 'You installed a new template.', 'Customization'),
(207, 1, 'Addons', '', ''),
(207, 2, 'Addons', 'You connected your back-office to the Addons platform using your PrestaShop Addons account.', 'Addons'),
(208, 1, 'Multi-boutiques', '', ''),
(208, 2, 'Multistores', 'You enabled the Multistores feature.', 'Multistores'),
(209, 1, 'Multi-boutiques', '', ''),
(209, 2, 'Multistores', 'You manage two shops with the Multistores feature.', 'Multistores'),
(210, 1, 'Multi-boutiques', '', ''),
(210, 2, 'Multistores', 'You manage two different groups of shops using the Multistores feature.', 'Multistores'),
(211, 1, 'Multi-boutiques', '', ''),
(211, 2, 'Multistores', 'You manage five shops with the Multistores feature.', 'Multistores'),
(212, 1, 'Multi-boutiques', '', ''),
(212, 2, 'Multistores', 'You manage five different groups of shops using the Multistores feature.', 'Multistores'),
(213, 1, 'Solutions de transport', '', ''),
(213, 2, 'Shipping', 'You offer three different shipping solutions (carriers) to your customers.', 'Shipping'),
(214, 1, 'Moyens de paiement', '', ''),
(214, 2, 'Payment', 'You offer three different payment methods to your customers.', 'Payment'),
(215, 1, 'Chiffre d\'affaires', '', ''),
(215, 2, 'Revenue', 'You get this badge when you reach 200 USD in sales.', 'Revenue'),
(216, 1, 'Chiffre d\'affaires', '', ''),
(216, 2, 'Revenue', 'You get this badge when you reach 1000 USD in sales.', 'Revenue'),
(217, 1, 'Chiffre d\'affaires', '', ''),
(217, 2, 'Revenue', 'You get this badge when you reach 1000 USD in sales.', 'Revenue'),
(218, 1, 'Chiffre d\'affaires', '', ''),
(218, 2, 'Revenue', 'You get this badge when you reach 200 USD in sales.', 'Revenue'),
(219, 1, 'Chiffre d\'affaires', '', ''),
(219, 2, 'Revenue', 'You get this badge when you reach 1000 USD in sales.', 'Revenue'),
(220, 1, 'Chiffre d\'affaires', '', ''),
(220, 2, 'Revenue', 'You get this badge when you reach 1000 USD in sales.', 'Revenue'),
(221, 1, 'Expérience', '', ''),
(221, 2, 'Days of Experience', 'You installed PrestaShop a month ago!', 'Days of Experience'),
(222, 1, 'Expérience', '', ''),
(222, 2, 'Days of Experience', 'You installed PrestaShop six months ago!', 'Days of Experience'),
(223, 1, 'Expérience', '', ''),
(223, 2, 'Days of Experience', 'You installed PrestaShop a year ago!', 'Days of Experience'),
(224, 1, 'Expérience', '', ''),
(224, 2, 'Days of Experience', 'You installed PrestaShop two years ago!', 'Days of Experience'),
(225, 1, 'Visiteurs', '', ''),
(225, 2, 'Visitors', 'You reached 10 visitors!', 'Visitors'),
(226, 1, 'Visiteurs', '', ''),
(226, 2, 'Visitors', 'You reached 100 visitors!', 'Visitors'),
(227, 1, 'Visiteurs', '', ''),
(227, 2, 'Visitors', 'You reached 1,000 visitors!', 'Visitors'),
(228, 1, 'Visiteurs', '', ''),
(228, 2, 'Visitors', 'You reached 10,000 visitors!', 'Visitors'),
(229, 1, 'Visiteurs', '', ''),
(229, 2, 'Visitors', 'You reached 100,000 visitors!', 'Visitors'),
(230, 1, 'Visiteurs', '', ''),
(230, 2, 'Visitors', 'You reached 1,000,000 visitors!', 'Visitors'),
(231, 1, 'Paniers', '', ''),
(231, 2, 'Customer Carts', 'Two carts have been created by visitors', 'Customer Carts'),
(232, 1, 'Paniers', '', ''),
(232, 2, 'Customer Carts', 'Ten carts have been created by visitors.', 'Customer Carts'),
(233, 1, 'Paniers', '', ''),
(233, 2, 'Customer Carts', 'A hundred carts have been created by visitors on your shop.', 'Customer Carts'),
(234, 1, 'Paniers', '', ''),
(234, 2, 'Customer Carts', 'A thousand carts have been created by visitors on your shop.', 'Customer Carts'),
(235, 1, 'Paniers', '', ''),
(235, 2, 'Customer Carts', '10,000 carts have been created by visitors.', 'Customer Carts'),
(236, 1, 'Paniers', '', ''),
(236, 2, 'Customer Carts', '100,000 carts have been created by visitors.', 'Customer Carts'),
(237, 1, 'Commandes', '', ''),
(237, 2, 'Orders', 'You received your first order.', 'Orders'),
(238, 1, 'Commandes', '', ''),
(238, 2, 'Orders', '10 orders have been placed through your online shop.', 'Orders'),
(239, 1, 'Commandes', '', ''),
(239, 2, 'Orders', 'You received 100 orders through your online shop!', 'Orders'),
(240, 1, 'Commandes', '', ''),
(240, 2, 'Orders', 'You received 1,000 orders through your online shop, congrats!', 'Orders'),
(241, 1, 'Commandes', '', ''),
(241, 2, 'Orders', 'You received 10,000 orders through your online shop, cheers!', 'Orders'),
(242, 1, 'Commandes', '', ''),
(242, 2, 'Orders', 'You received 100,000 orders through your online shop!', 'Orders'),
(243, 1, 'Messages Clients', '', ''),
(243, 2, 'Customer Service Threads', 'You received  your first customer\'s message.', 'Customer Service Threads'),
(244, 1, 'Messages Clients', '', ''),
(244, 2, 'Customer Service Threads', 'You received 10 messages from your customers.', 'Customer Service Threads'),
(245, 1, 'Messages Clients', '', ''),
(245, 2, 'Customer Service Threads', 'You received 100 messages from your customers.', 'Customer Service Threads'),
(246, 1, 'Messages Clients', '', ''),
(246, 2, 'Customer Service Threads', 'You received 1,000 messages from your customers.', 'Customer Service Threads'),
(247, 1, 'Messages Clients', '', ''),
(247, 2, 'Customer Service Threads', 'You received 10,000 messages from your customers.', 'Customer Service Threads'),
(248, 1, 'Messages Clients', '', ''),
(248, 2, 'Customer Service Threads', 'You received 100,000 messages from your customers.', 'Customer Service Threads'),
(249, 1, 'Clients', '', ''),
(249, 2, 'Customers', 'You got the first customer registered on your shop!', 'Customers'),
(250, 1, 'Clients', '', ''),
(250, 2, 'Customers', 'You have over 10 customers registered on your shop.', 'Customers'),
(251, 1, 'Clients', '', ''),
(251, 2, 'Customers', 'You have over 100 customers registered on your shop.', 'Customers'),
(252, 1, 'Clients', '', ''),
(252, 2, 'Customers', 'You have over 1,000 customers registered on your shop.', 'Customers'),
(253, 1, 'Clients', '', ''),
(253, 2, 'Customers', 'You have over 10,000 customers registered on your shop.', 'Customers'),
(254, 1, 'Clients', '', ''),
(254, 2, 'Customers', 'You have over 100,000 customers registered on your shop.', 'Customers'),
(260, 1, 'Amérique du Nord', '', ''),
(260, 2, 'North America', 'You got your first sale in North America', 'North America'),
(261, 1, 'Océanie', '', ''),
(261, 2, 'Oceania', 'You got your first sale in Oceania', 'Oceania'),
(262, 1, 'Asie', '', ''),
(262, 2, 'Asia', 'You got your first sale in Asia', 'Asia'),
(263, 1, 'Amérique du Sud', '', ''),
(263, 2, 'South America', 'You got your first sale in South America', 'South America'),
(264, 1, 'Afrique', '', ''),
(264, 2, 'Africa', 'You got your first sale in Africa', 'Africa'),
(265, 1, 'Maghreb', '', ''),
(265, 2, 'Maghreb', 'You got your first sale in Maghreb', 'Maghreb'),
(266, 1, 'Equipe', '', ''),
(266, 2, 'Your Team\'s Employees', 'First employee account added to your shop', 'Your Team\'s Employees'),
(267, 1, 'Equipe', '', ''),
(267, 2, 'Your Team\'s Employees', '3 employee accounts added to your shop', 'Your Team\'s Employees'),
(268, 1, 'Equipe', '', ''),
(268, 2, 'Your Team\'s Employees', '5 employee accounts added to your shop', 'Your Team\'s Employees'),
(269, 1, 'Equipe', '', ''),
(269, 2, 'Your Team\'s Employees', '10 employee accounts added to your shop', 'Your Team\'s Employees'),
(270, 1, 'Equipe', '', ''),
(270, 2, 'Your Team\'s Employees', '20 employee accounts added to your shop', 'Your Team\'s Employees'),
(271, 1, 'Equipe', '', ''),
(271, 2, 'Your Team\'s Employees', '40 employee accounts added to your shop', 'Your Team\'s Employees'),
(272, 1, 'Photos produits', '', ''),
(272, 2, 'Product Pictures', 'First photo added to your catalog', 'Product Pictures'),
(273, 1, 'Photos produits', '', ''),
(273, 2, 'Product Pictures', '50 photos added to your catalog', 'Product Pictures'),
(274, 1, 'Photos produits', '', ''),
(274, 2, 'Product Pictures', '100 photos added to your catalog', 'Product Pictures'),
(275, 1, 'Photos produits', '', ''),
(275, 2, 'Product Pictures', '1,000 photos added to your catalog', 'Product Pictures'),
(276, 1, 'Photos produits', '', ''),
(276, 2, 'Product Pictures', '10,000 photos added to your catalog', 'Product Pictures'),
(277, 1, 'Photos produits', '', ''),
(277, 2, 'Product Pictures', '50,000 photos added to your catalog', 'Product Pictures'),
(278, 1, 'Personnalisation', '', ''),
(278, 2, 'Customization', 'First CMS page added to your catalog', 'Customization'),
(279, 1, 'Règles panier', '', ''),
(279, 2, 'Cart Rules', 'First cart rules configured on your shop', 'Cart Rules'),
(280, 1, 'Règles panier', '', ''),
(280, 2, 'Cart Rules', 'You have 10 cart rules configured on your shop', 'Cart Rules'),
(281, 1, 'Règles panier', '', ''),
(281, 2, 'Cart Rules', 'You have 100 cart rules configured on your shop', 'Cart Rules'),
(282, 1, 'Règles panier', '', ''),
(282, 2, 'Cart Rules', 'You have 500 cart rules configured on your shop', 'Cart Rules'),
(283, 1, 'Règles panier', '', ''),
(283, 2, 'Cart Rules', 'You have 1,000 cart rules configured on your shop', 'Cart Rules'),
(284, 1, 'Règles panier', '', ''),
(284, 2, 'Cart Rules', 'You have 5,000 cart rules configured on your shop', 'Cart Rules'),
(285, 1, 'Commandes à l\'étranger', '', ''),
(285, 2, 'International Orders', 'First international order placed on your shop.', 'International Orders'),
(286, 1, 'Commandes à l\'étranger', '', ''),
(286, 2, 'International Orders', '10 international orders placed on your shop.', 'International Orders'),
(287, 1, 'Commandes à l\'étranger', '', ''),
(287, 2, 'International Orders', '100 international orders placed on your shop!', 'International Orders'),
(288, 1, 'Commandes à l\'étranger', '', ''),
(288, 2, 'International Orders', '1,000 international orders placed on your shop!', 'International Orders'),
(289, 1, 'Commandes à l\'étranger', '', ''),
(289, 2, 'International Orders', '5,000 international orders placed on your shop!', 'International Orders'),
(290, 1, 'Commandes à l\'étranger', '', ''),
(290, 2, 'International Orders', '10,000 international orders placed on your shop!', 'International Orders'),
(291, 1, 'Boutique Physique', '', ''),
(291, 2, 'Store', 'First store configured on your shop!', 'Store'),
(292, 1, 'Boutique Physique', '', ''),
(292, 2, 'Store', 'You have 2 stores configured on your shop', 'Store'),
(293, 1, 'Boutique Physique', '', ''),
(293, 2, 'Store', 'You have 5 stores configured on your shop', 'Store'),
(294, 1, 'Boutique Physique', '', ''),
(294, 2, 'Store', 'You have 10 stores configured on your shop', 'Store'),
(295, 1, 'Boutique Physique', '', ''),
(295, 2, 'Store', 'You have 20 stores configured on your shop', 'Store'),
(296, 1, 'Boutique Physique', '', ''),
(296, 2, 'Store', 'You have 50 stores configured on your shop', 'Store'),
(297, 1, 'Webservice x1', '', ''),
(297, 2, 'Webservice x1', 'First webservice account added to your shop', 'WebService'),
(298, 1, 'Webservice x2', '', ''),
(298, 2, 'Webservice x2', '2 webservice accounts added to your shop', 'WebService'),
(299, 1, 'Webservice x3', '', ''),
(299, 2, 'Webservice x3', '3 webservice accounts added to your shop', 'WebService'),
(300, 1, 'Webservice x4', '', ''),
(300, 2, 'Webservice x4', '4 webservice accounts added to your shop', 'WebService'),
(301, 1, 'Alliance Payment installed', '', ''),
(301, 2, 'Alliance Payment installed', 'You have installed the Alliance Payment module', 'Partners'),
(302, 1, 'Alliance Payment configured', '', ''),
(302, 2, 'Alliance Payment configured', 'You have configured the Alliance Payment module', 'Partners'),
(303, 1, 'Alliance Payment active', '', ''),
(303, 2, 'Alliance Payment active', 'Your Alliance Payment module is active', 'Partners'),
(304, 1, 'Alliance Payment very active', '', ''),
(304, 2, 'Alliance Payment very active', 'Your Alliance Payment module is very active', 'Partners'),
(305, 1, 'Blue Pay installed', '', ''),
(305, 2, 'Blue Pay installed', 'You have installed the Blue Pay module', 'Partners'),
(306, 1, 'Blue Pay configured', '', ''),
(306, 2, 'Blue Pay configured', 'You have configured the Blue Pay module', 'Partners'),
(307, 1, 'Blue Pay active', '', ''),
(307, 2, 'Blue Pay active', 'Your Blue Pay module is active', 'Partners'),
(308, 1, 'Blue Pay very active', '', ''),
(308, 2, 'Blue Pay very active', 'Your Blue Pay module is very active', 'Partners'),
(309, 1, 'Europe', '', ''),
(309, 2, 'Europe', 'You got your first sale in  Europe!', 'Europe');
