
-- --------------------------------------------------------

--
-- Structure de la table `vj9e_manufacturer_lang`
--

CREATE TABLE `vj9e_manufacturer_lang` (
  `id_manufacturer` int(10) UNSIGNED NOT NULL,
  `id_lang` int(10) UNSIGNED NOT NULL,
  `description` text,
  `short_description` text,
  `meta_title` varchar(128) DEFAULT NULL,
  `meta_keywords` varchar(255) DEFAULT NULL,
  `meta_description` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `vj9e_manufacturer_lang`
--

INSERT INTO `vj9e_manufacturer_lang` (`id_manufacturer`, `id_lang`, `description`, `short_description`, `meta_title`, `meta_keywords`, `meta_description`) VALUES
(1, 1, '', '', '', '', ''),
(1, 2, '', '', 'Minnie - Les héros de nos bambins', 'minnie,housse de couette minnie,vetement minnie,housse de couette minnie pas cher,vetement minnie pas cher', 'Notre collection de vetement, housse de couette minnie et encore d\'autre'),
(2, 1, '', '', '', '', ''),
(2, 2, '', '', 'Mickey', 'Mickey', 'licence mickey'),
(3, 1, '', '', '', '', ''),
(3, 2, '', '', 'avengers', 'avengers', 'la colonie avengers est chez les héros de nos bambins'),
(4, 1, '', '', '', '', ''),
(4, 2, '', '', 'reine des neiges', '', 'l\'univers de la reine des neiges est chez les héros de nos bambins'),
(5, 1, '', '', '', '', ''),
(5, 2, '', '', 'spiderman', '', 'Les aventures de spiderman sont chez les héros de nos bambins'),
(6, 1, '', '', '', '', ''),
(6, 2, '', '', 'princess', 'Princess', 'Toutes les princess disney sont disponibles chez les héros de nos bambins'),
(7, 1, '', '', '', '', ''),
(7, 2, '', '', 'Batman', '', 'Batman est le super héros à ne pas louper'),
(8, 1, '', '', '', '', ''),
(8, 2, '', '', 'pat patrouille', 'pat patrouille,paw patrol', 'La tribu pat patrouille sont ici chez les héros de nos bambins'),
(9, 1, '', '', '', '', ''),
(9, 2, '', '', 'minions', 'minions', 'on ne les présente plus les minions sauront vous amuser jour et nuit'),
(10, 1, '', '', '', '', ''),
(10, 2, '', '', 'shimmer and shime', '', 'la licence shimmer and shine saura vous plaire '),
(11, 1, '', '', '', '', ''),
(11, 2, '', '', '', '', ''),
(12, 1, '', '', '', '', ''),
(12, 2, '', '', '', '', ''),
(13, 1, '', '', '', '', ''),
(13, 2, '', '', '', '', ''),
(14, 1, '', '', '', '', ''),
(14, 2, '', '', '', '', ''),
(15, 1, '', '', '', '', ''),
(15, 2, '', '', '', '', ''),
(16, 1, '', '', '', '', ''),
(16, 2, '', '', '', '', ''),
(17, 1, '', '', '', '', ''),
(17, 2, '', '', 'Little Mole - LES HEROS DE NOS BAMBINS', '', 'L\'univers Little Mole est à découvrir chez Les Héros de Nos Bambins'),
(18, 1, '', '', '', '', ''),
(18, 2, '', '', 'Les Simpsons - LES HEROS DE NOS BAMBINS', 'simpsons,simpsons pas cher,simpsons discount', 'Découvrez l\'univers des Simpsons chez les héros de nos bambins'),
(19, 1, '', '', '', '', ''),
(19, 2, '', '', 'ANIMALS - LES HEROS DE NOS BAMBINS', 'animals,animals pas cher,animals discount', 'Découvrez l\'univers des Animals chez les héros de nos bambins'),
(20, 1, '', '', '', '', ''),
(20, 2, '', '', 'ANGRY BIRDS - LES HEROS DE NOS BAMBINS', 'angry birds,angry birds pas cher,angry birds discount', 'Découvrez l\'ensemble de la collection angry birds chez les héros de nos bambins'),
(21, 1, '', '', '', '', ''),
(21, 2, '', '', 'ASSASSIN\'S CREED - LES HEROS DE NOS BAMBINS', 'assassin\'s creed,assassin\'s creed pas cher,assassin\'s creed discount', 'Découvrez l\'univers ASSASSIN\'S CREED chez les héros de nos bambins'),
(22, 1, '', '', '', '', ''),
(22, 2, '', '', 'BABY SHARK - LES HEROS DE NOS BAMBINS', 'baby shark,baby shark pas cher,baby shark discount', 'Découvrez BABY SHARK chez les héros de nos bambins'),
(23, 1, '', '', '', '', ''),
(23, 2, '', '', 'BARBIE - LES HEROS DE NOS BAMBINS', 'barbie,barbie pas cher,barbie discount', 'Barbie est présente chez les héros de nos bambins'),
(24, 1, '', '', '', '', ''),
(24, 2, '', '', 'BEN 10 - LES HEROS DE NOS BAMBINS', 'ben 10,ben 10 pas cher,ben 10 discount', 'L\'univers de BEN 10 est disponible chez les héros de nos bambins'),
(25, 1, '', '', '', '', ''),
(25, 2, '', '', 'BING - LES HEROS DE NOS BAMBINS', 'bing,bing pas cher,bing discount', 'Découvrez la collection BING chez les héros de nos bambins'),
(26, 1, '', '', '', '', ''),
(26, 2, '', '', 'BOB LE BRICOLEUR - LES HEROS DE NOS BAMBINS', 'bob bricoleur,bpb le bricoleur,bob bricoleur pas cher,bob le bricoleur pas cher,bob bricoleur discount,bob le bricoleur discount', 'Découvrez la collection BOB LE BRICOLEUR chez les héros de nos bambins'),
(27, 1, '', '', '', '', ''),
(27, 2, '', '', 'LOONEY TUNES - LES HEROS DE NOS BAMBINS', 'looney tunes,looney tunes pas cher,looney tunes discount', 'Découvrez la collection LOONEY TUNES chez les héros de nos bambins'),
(28, 1, '', '', '', '', ''),
(28, 2, '', '', 'CHERIF CALLIE - LES HEROS DE NOS BAMBINS', 'cherif callie,cherif callie pas cher,cherif callie discount,chérif callie,chérif callie pas cher,chérif callie discount', 'L\'univers de CHERIF CALLIE vous attend chez les héros de nos bambins'),
(29, 1, '', '', '', '', ''),
(29, 2, '', '', '101 DALMATIENS - LES HEROS DE NOS BAMBINS', '101 dalmatiens,101 dalmatiens pas cher,101 dalmatiens discount', 'Découvrez les 101 DALMATIENS chez les héros de nos bambins'),
(30, 1, '', '', '', '', ''),
(30, 2, '', '', 'LES INDESTRUCTIBLES - LES HEROS DE NOS BAMBINS', 'les indestructibles,les indestructibles pas cher,les indestructibles discount', 'Découvrez l\'univers des INDESTRUCTIBLES chez les héros de nos bambins'),
(31, 1, '', '', '', '', ''),
(31, 2, '', '', 'ALADDIN - LES HEROS DE NOS BAMBINS', 'aladdin,aladdin pas cher,aladdin discount', 'Découvrez ALADDIN chez les héros de nos bambins'),
(32, 1, '', '', '', '', ''),
(32, 2, '', '', 'BAMBI - LES HEROS DE NOS BAMBINS', 'bambi,bambi pas cher,bambi discount', 'Découvrez BAMBI chez les héros de nos bambins'),
(33, 1, '', '', '', '', ''),
(33, 2, '', '', 'COCO - LES HEROS DE NOS BAMBINS', 'coco,coco pas cher,coco discount', 'Découvrez COCO chez les héros de nos bambins'),
(34, 1, '', '', '', '', ''),
(34, 2, '', '', 'LA FEE CLOCHETTE - LES HEROS DE NOS BAMBINS', 'la fée clochette,la fée clochette pas cher,la fée clochette discount', 'Découvrez la FEE CLOCHETTE chez les héros de nos bambins'),
(35, 1, '', '', '', '', ''),
(35, 2, '', '', 'DONALD - LES HEROS DE NOS BAMBINS', 'donald,donald pas cher,donald discount', 'Découvrez DONALD chez les héros de nos bambins'),
(36, 1, '', '', '', '', ''),
(36, 2, '', '', 'DUMBO - LES HEROS DE NOS BAMBINS', 'dumbo,dumbo pas cher,dumbo discount', 'Découvrez DUMBO chez les héros de nos bambins'),
(37, 1, '', '', '', '', ''),
(37, 2, '', '', 'ELENA - LES HEROS DE NOS BAMBINS', 'elena,elena pas cher,elena discount', 'Découvrez le monde d\'ELENA chez les héros de nos bambins'),
(38, 1, '', '', '', '', ''),
(38, 2, '', '', 'TOY STORY - LES HEROS DE NOS BAMBINS', 'toy strory,toy story pas cher,toy story discount', 'Découvrez TOY STORY chez les héros de nos bambins'),
(39, 1, '', '', '', '', ''),
(39, 2, '', '', 'MARIE - LES HEROS DE NOS BAMBINS', 'marie,marie pas cher,marie discount', 'Découvrez l\'univers de MARIE des ARISTOCHATS chez les héros de nos bambins'),
(40, 1, '', '', '', '', ''),
(40, 2, '', '', 'WINNIE L\'OURSON - LES HEROS DE NOS BAMBINS', 'winnie,winnie pas cher,winnie discount', 'Découvrez WINNIE L\'OURSON chez les héros de nos bambins'),
(41, 1, '', '', '', '', ''),
(41, 2, '', '', 'LA GARDE DU LION - LES HEROS DE NOS BAMBINS', 'la garde du lion,la garde du lion pas cher,la garde du lion discount', 'Découvrez LA GARDE DU LION chez les héros de nos bambins'),
(42, 1, '', '', '', '', ''),
(42, 2, '', '', 'PLANES - LES HEROS DE NOS BAMBINS', 'planes,planes pas cher,planes discount', 'Découvrez PLANES chez les héros de nos bambins'),
(43, 1, '', '', '', '', ''),
(43, 2, '', '', 'LADY - LES HEROS DE NOS BAMBINS', 'lady,lady pas cher,lady discount', 'Découvrez l\'univers de LADY chez les héros de nos bambins'),
(44, 1, '', '', '', '', ''),
(44, 2, '', '', 'TSUM TSUM - LES HEROS DE NOS BAMBINS', 'tsum tsum,tsum tsum pas cher,tsum tsum discount', 'Découvrez l\'univers des TSUM TSUM chez les héros de nos bambins'),
(45, 1, '', '', '', '', ''),
(45, 2, '', '', 'VAIANA - LES HEROS DE NOS BAMBINS', 'vaiana,vaiana pas cher,vaiana discount', 'Découvrez VAIANA chez les héros de nos bambins'),
(46, 1, '', '', '', '', ''),
(46, 2, '', '', 'VAMPIRINA - LES HEROS DE NOS BAMBINS', 'vampirina,vampirina pas cher', 'Découvrez VAMPIRINA chez les héros de nos bambins'),
(47, 1, '', '', '', '', ''),
(47, 2, '', '', 'DOCTEUR LA PELUCHE - LES HEROS DE NOS BAMBINS', 'docteur la peluche,docteur la peluche pas cher,docteur la peluche discount', 'Découvrez DOCTEUR LA PELUCHE chez les héros de nos bambins'),
(48, 1, '', '', '', '', ''),
(48, 2, '', '', 'EMOJI - LES HEROS DE NOS BAMBINS', 'emoji,emoji pas cher,emoji discount', 'Découvrez EMOJI chez les héros de nos bambins'),
(49, 1, '', '', '', '', ''),
(49, 2, '', '', 'ENCHANTIMALS - LES HEROS DE NOS BAMBINS', 'enchantimals,enchantimals pas cher,enchantimals discount', 'Découvrez les ENCHANTIMALS chez les héros de nos bambins'),
(50, 1, '', '', '', '', ''),
(50, 2, '', '', 'WOODLAND PRINCESS  - LES HEROS DE NOS BAMBINS', 'woodland princess,woodland princess pas cher,woodland princess discount', 'Découvrez WOODLAND PRINCESS chez les héros de nos bambins'),
(51, 1, '', '', '', '', ''),
(51, 2, '', '', 'FC BAYERN MUNICH - LES HEROS DE NOS BAMBINS', 'bayern munich,bayern munich pas cher,bayern munich discount', 'Découvrez les accessoires du BAYERN DE MUNICH  chez les heros de nos bambins'),
(52, 1, '', '', '', '', ''),
(52, 2, '', '', 'FORTNITE - LES HEROS DE NOS BAMBINS', 'fortnite,fortnite pas cher,fortnite discount', 'Découvrez l\'univers de FORTNITE  chez les héros de nos bambins'),
(53, 1, '', '', '', '', ''),
(53, 2, '', '', 'HARRY POTTER - LES HEROS DE NOS BAMBINS', 'harry potter,harry potter pas cher,harry potter discount', 'Découvrez HARRY POTTER chez les héros de nos bambins'),
(54, 1, '', '', '', '', ''),
(54, 2, '', '', 'HELLO KITTY - LES HEROS DE NOS BAMBINS', 'hello kitty,hello kitty pas cher,hello kitty discount', 'Découvrez HELLO KITTY chez les héros de nos bambins'),
(55, 1, '', '', '', '', ''),
(55, 2, '', '', 'LES SCHTROUMPFS - LES HEROS DE NOS BAMBINS', 'les schtroumpfs,les schtroumpfs pas cher,les schtroumpfs discount', 'Découvrez les SCHTROUMPFS chez les héros de nos bambins'),
(56, 1, '', '', '', '', ''),
(56, 2, '', '', 'DRAGON - LES HEROS DE NOS BAMBINS', 'dragon,dragon pas cher,dragon discount', 'Découvrez l\'univers de DRAGON chez les héros de nos bambins'),
(57, 1, '', '', '', '', ''),
(57, 2, '', '', 'JAKE - LES HEROS DE NOS BAMBINS', 'jake,jake pas cher,jake discount', 'Découvrez JAKE chez les héros de nos bambins'),
(58, 1, '', '', '', '', ''),
(58, 2, '', '', 'JUVENTUS - LES HEROS DE NOS BAMBINS', 'juventus,juventus pas cher,juventus discount', 'Découvrez l\'univers de la JUVENTTUS chez les héros de nos bambins'),
(59, 1, '', '', '', '', ''),
(59, 2, '', '', 'JURASSIC PARK - LES HEROS DE NOS BAMBINS', 'jurassic park,jurassic park pas cher,jurassic park discount', 'Découvrez l\'univers de JURASSIC PARK chez les héros de nos bambins'),
(60, 1, '', '', '', '', ''),
(60, 2, '', '', 'BLAZE - LES HEROS DE NOS BAMBINS', 'blaze,blaze pas cher,blaze discount', 'Découvrez BLAZE chez les héros de nos bambins'),
(61, 1, '', '', '', '', ''),
(61, 2, '', '', 'LEGO - LES HEROS DE NOS BAMBINS', 'lego,lego pas cher,lego discount', 'Découvrez les accessoires LEGO chez les héros de nos bambins'),
(62, 1, '', '', '', '', ''),
(62, 2, '', '', 'PET SHOP - LES HEROS DE NOS BAMBINS', 'pet shop,pet shop pas cher,pet shop discount', 'Découvrez l\'univers PET SHOP chez les héros de nos bambins'),
(63, 1, '', '', '', '', ''),
(63, 2, '', '', 'LOL - LES HEROS DE NOS BAMBINS', 'lol,lol pas cher,lol discount', 'Découvrez les accessoires LOL chez les héros de nos bambins'),
(64, 1, '', '', '', '', ''),
(64, 2, '', '', 'MASHA ET MICHKA - LES HEROS DE NOS BAMBINS', 'masha et michka,masha et michka pas cher,masha et michka discount', 'Découvrez MASHA ET MICHKA chez les héros de nos bambins'),
(65, 1, '', '', '', '', ''),
(65, 2, '', '', 'MIA AND MI - LES HEROS DE NOS BAMBINS', 'mia and me,mia and me pas cher,mia and me discount', 'Découvrez MIA AND ME chez les héros de nos bambins'),
(66, 1, '', '', '', '', ''),
(66, 2, '', '', 'PINGOUINS DE MADAGASCAR - LES HEROS DE NOS BAMBINS', 'pingouins de madagascar,pingouins de madagascar pas cher,pingouins de madagascar discount', 'Découvrez les PINGOUINS DE MADAGASCAR chez les héros de nos bambins'),
(67, 1, '', '', '', '', ''),
(67, 2, '', '', 'MINECRAFT - LES HEROS DE NOS BAMBINS', 'minecraft,minecraft pas cher,minecraft discount', 'Découvrez l\'univers de MINECRAFT chez les héros de nos bambins'),
(68, 1, '', '', '', '', ''),
(68, 2, '', '', 'PRINCESSE NELLA - LES HEROS DE NOS BAMBINS', 'princesse nella,princesse nella pas cher,princess nella discount', 'Découvrez la PRINCESSE NELLA chez les héros de nos bambins'),
(69, 1, '', '', '', '', ''),
(69, 2, '', '', 'PJ MASKS - LES HEROS DE NOS BAMBINS', 'pj masks,pj masks pas cher,pj masks discount', 'Découvrez les PJ MASKS chez les héros de nos bambins'),
(70, 1, '', '', '', '', ''),
(70, 2, '', '', 'PLAYSTATION - LES HEROS DE NOS BAMBINS', 'playstation,playstation pas cher,playstation discount', 'Découvrez notre sélection d\'accessoires PLAYSTATION chez les héros de nos bambins'),
(71, 1, '', '', '', '', ''),
(71, 2, '', '', 'POKEMON - LES HEROS DE NOS BAMBINS', 'pokemon,pokemon pas cher,pokemon discount', 'Découvrez les POKEMONS chez les héros de nos bambins'),
(72, 1, '', '', '', '', ''),
(72, 2, '', '', 'PAT LE FACTEUR - LES HEROS DE NOS BAMBINS', 'pat le facteur,pat le facteur pas cher,pat le facteur discount', 'Découvrez PAT LE FACTEUR chez les héros de nos bambins'),
(73, 1, '', '', '', '', ''),
(73, 2, '', '', 'REAL MADRID - LES HEROS DE NOS BAMBINS', 'real madrid,real madrid pas cher,real madrid discount', 'Découvrez notre sélection du REAL MADRID chez les héros de nos bambins'),
(74, 1, '', '', '', '', ''),
(74, 2, '', '', 'RUSTY RIVETS - LES HEROS DE NOS BAMBINS', 'rusty rivets,rusty rivets pas cher,rusty rivets discount', 'Découvrez RUSTY RIVETS chez les héros de nos bambins'),
(75, 1, '', '', '', '', ''),
(75, 2, '', '', 'SAM LE POMPIER - LES HEROS DE NOS BAMBINS', 'sam le pompier,sam le pompier pas cher,sam le pompier discount', 'Découvrez SAM LE POMPIER chez les héros de nos bambins'),
(76, 1, '', '', '', '', ''),
(76, 2, '', '', 'SCOOBY DOO - LES HEROS DE NOS BAMBINS', 'scooby doo,scooby doo pas cher,scooby doo discount', 'Découvrez SCOOBY DOO chez les héros de nos bambins'),
(77, 1, '', '', '', '', ''),
(77, 2, '', '', 'BOB L\'EPONGE - LES HEROS DE NOS BAMBINS', 'bob l\'éponge,bob l\'éponge pas cher,bob l\'éponge discount', 'Découvrez BOB L\'EPONGE  chez les heros de nos bambins'),
(78, 1, '', '', '', '', ''),
(78, 2, '', '', 'STAR WARS - LES HEROS DE NOS BAMBINS', 'star wars,star wars pas cher,star wars discount', 'Découvrez STAR WARS chez les héros de nos bambins'),
(79, 1, '', '', '', '', ''),
(79, 2, '', '', 'SUPER MARIO - LES HEROS DE NOS BAMBINS', 'super mario,super mario pas cher,super mario discount', 'Découvrez SUPER MARIO chez les héros de nos bambins'),
(80, 1, '', '', '', '', ''),
(80, 2, '', '', 'SUPER WINGS - LES HEROS DE NOS BAMBINS', 'super wings,super wings pas cher,super wings discount', 'Découvrez LES SUPER WINGS chez les héros de nos bambins'),
(81, 1, '', '', '', '', ''),
(81, 2, '', '', 'SUPERMAN - LES HEROS DE NOS BAMBINS', 'superman,superman pas cher,superman discount', 'Découvrez SUPERMAN chez les héros de nos bambins'),
(82, 1, '', '', '', '', ''),
(82, 2, '', '', 'THOMAS LE TRAIN - LES HEROS DE NOS BAMBINS', 'thomas le train,thomas le train pas cher,thomas le train discount', 'Découvrez THOMAS LE TRAIN chez les héros de nos bambins'),
(83, 1, '', '', '', '', ''),
(83, 2, '', '', 'TORTUES NINJA - LES HEROS DE NOS BAMBINS', 'tortues ninja,tortues ninja pas cher,tortues ninja discount', 'Découvrez LES TORTUES NINJA chez les héros de nos bambins'),
(84, 1, '', '', '', '', ''),
(84, 2, '', '', 'SUPER HERO GIRLS -LES HEROS DE NOS BAMBINS', 'super héros girls,super héros girls pas cher,super héros girls discount', 'Découvrez SUPER HERO GIRLS chez les héros de nos bambins'),
(85, 1, '', '', '', '', ''),
(85, 2, '', '', 'TOM AND JERRY - LES HEROS DE NOS BAMBINS', 'tom and jerry,tom and jerry pas cher,tom and jerry discount', 'Découvrez TOM AND JERRY chez les héros de nos bambins'),
(86, 1, '', '', '', '', ''),
(86, 2, '', '', 'TRANSFORMERS - LES HEROS DE NOS BAMBINS', 'transformers,transformers pas cher,transformers discount', 'Découvrez TRANSFORMERS chez les héros de nos bambins'),
(87, 1, '', '', '', '', ''),
(87, 2, '', '', 'TROLLS - LES HEROS DE NOS BAMBINS', 'trolls,trolls pas cher,trolls discount', 'Découvrez TROLLS chez les héros de nos bambins'),
(88, 1, '', '', '', '', ''),
(88, 2, '', '', 'GAME OF THRONES - LES HEROS DE NOS BAMBINS', 'game of thrones,game of thrones pas cher, game of thrones discount', 'Découvrez GAME OF THRONES chez les héros de nos bambins'),
(89, 1, '', '', '', '', ''),
(89, 2, '', '', 'UNICORN - LES HEROS DE NOS BAMBINS', 'unicorn,unicorn pas cher,unicorn discount', 'Découvrez UNICORN chez les héros de nos bambins'),
(90, 1, '', '', '', '', ''),
(90, 2, '', '', 'CITIES - LES HEROS DE NOS BAMBINSDé', 'cities,cities pas cher,cities discount', 'Découvrez CITIES chez les héros de nos bambins'),
(91, 1, '', '', '', '', ''),
(91, 2, '', '', 'YO-KAI WATCH - LES HEROS DE NOS BAMBINS', 'yo-kai watch,yo-kai watch pas cher,yo-kai watch discount', 'Découvrez YO-KAI WATCH chez les héros de nos bambins'),
(92, 1, '', '', '', '', ''),
(92, 2, '', '', 'ZOOTOPIE - LES HEROS DE NOS BAMBINS', 'zootopie,zootopie pas cher,zootopie discount', 'Découvrez ZOOTOPIE chez les héros de nos bambins');
