
-- --------------------------------------------------------

--
-- Structure de la table `vj9e_ybc_blog_post_lang`
--

CREATE TABLE `vj9e_ybc_blog_post_lang` (
  `id_post` int(11) DEFAULT NULL,
  `id_lang` int(11) DEFAULT NULL,
  `title` varchar(2000) CHARACTER SET utf8 DEFAULT NULL,
  `url_alias` varchar(700) COLLATE latin1_general_ci NOT NULL,
  `description` text CHARACTER SET utf8,
  `short_description` text CHARACTER SET utf8,
  `meta_keywords` varchar(5000) CHARACTER SET utf8 DEFAULT NULL,
  `meta_description` text CHARACTER SET utf8
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

--
-- Déchargement des données de la table `vj9e_ybc_blog_post_lang`
--

INSERT INTO `vj9e_ybc_blog_post_lang` (`id_post`, `id_lang`, `title`, `url_alias`, `description`, `short_description`, `meta_keywords`, `meta_description`) VALUES
(1, 1, 'Sample blog title', 'sample-post1', '<p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.<br />Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.<br />Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.<br />Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.<br />Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>', 'Lorem,minim', 'Sample post meta description'),
(1, 2, 'Bandes annonces des sorties au cinéma', 'sample-post1', '<p></p>\n<p></p>', '<p>Toutes les bandes annonces de l\'année 2019, comme Dragons, Alladin, le Roi Lion, Dumbo, Star Wars, Avengers, Toy Story, la Reine des neiges, spiderman.</p>\n<p>Nous sommes heureux de vous les présenter!!!</p>', 'Lorem,minim', 'Découvrez toutes les bandes annonces de cinéma allociné des supers héros chez les héros de nos bambins.  Dragons, Alladin, Roi Lion, Dumbo, Star wars, Avengers, Toys story, Reine des neiges, Spiderman'),
(3, 1, 'Une année de rêve chez Disney !!', 'une-annee-de-reve-chez-disney-', '', '<p>Une année d\'exception offerte par disney vous remplira les yeux. Ouvrez bien grands vos yeux !!!! </p>\n<p></p>\n<p></p><video width=\"300\" height=\"150\"><source src=\"/img/cms/2019,%20une%20ann%C3%A9e%20de%20r%C3%AAve%20pour%20les%20fans%20Disney.mp4\" type=\"video/mp4\"></source></video>', 'disney,roi lion,dumbo,toy story4,toy story,le monde de ralph2', 'Vivez une année de rêve avec Disney ...'),
(2, 1, 'Bande annonce Dragons 3', 'bande-annonce-dragons-3', '<p>Dragons 3 : Le monde caché</p>\n<p>La bande annonce du nouveau dessin animé dragons 3 est chez les héros de nos bambins. Ce chef d\'oeuvre sortira dans les salles le 6 Février 2019</p>\n<p></p>\n<p></p>\n<p></p><video width=\"300\" height=\"150\"><source src=\"/img/cms/Dragons%203%20%20%20Le%20Monde%20Cach%C3%A9%20%20%20Bande-Annonce%20VF%20%5BAu%20cin%C3%A9ma%20le%206%20F%C3%A9vrier%5D.mp4\" type=\"video/mp4\"></source></video>', '<p>Bande annonce en français dragons 3 </p>', 'dragons,dragon,dragons3,dragon3,dragons 3, dragon 3,dessin animé,cinéma', 'Découvrez la bande annonce de Dragons 3 en salle à partir du 6 février 2019'),
(2, 2, 'Bande annonce Dragons 3', 'bande-annonce-dragons-3', '<p>Dragons 3 : Le monde caché</p>\n<p>La bande annonce du nouveau dessin animé dragons 3 est chez les héros de nos bambins. Ce chef d\'oeuvre sortira dans les salles le 6 Février 2019</p>\n<p></p>\n<p></p>\n<p></p>\n<p></p><video width=\"424\" height=\"212\"><source src=\"/img/cms/Dragons%203%20%20%20Le%20Monde%20Cach%C3%A9%20%20%20Bande-Annonce%20VF%20%5BAu%20cin%C3%A9ma%20le%206%20F%C3%A9vrier%5D.mp4\" type=\"video/mp4\"></source></video><p><span style=\"color:#333333;font-family:Arial, sans-serif;font-size:16px;\">Harold est maintenant le chef de Berk au côté d’Astrid et Krokmou, en tant que dragon, est devenu le leader de son espèce. Ils réalisent enfin leurs rêves de vivre en paix entre vikings et dragons. Mais lorsque l’apparition soudaine d’une Furie Eclair coïncide avec la plus grande menace que le village n’ait jamais connue, Harold et Krokmou sont forcés de quitter leur village pour un voyage dans un monde caché dont ils n’auraient jamais soupçonnés l’existence. Alors que leurs véritables destins se révèlent, dragons et vikings vont se battre ensemble jusqu’au bout du monde pour protéger tout ce qu’ils chérissent</span></p>', '<p>Bande annonce en français dragons 3 </p>', 'dragons,dragon,dragons3,dragon3,dragons 3, dragon 3,dessin animé,cinéma', 'Découvrez la bande annonce de Dragons 3 en salle à partir du 6 février 2019'),
(3, 2, 'Une année de rêve chez Disney !!', 'une-annee-de-reve-chez-disney-', '', '<p>Une année d\'exception offerte par disney vous remplira les yeux. Ouvrez bien grands vos yeux !!!! </p>\n<p></p>\n<p></p><video width=\"300\" height=\"150\"><source src=\"/img/cms/2019,%20une%20ann%C3%A9e%20de%20r%C3%AAve%20pour%20les%20fans%20Disney.mp4\" type=\"video/mp4\"></source></video>', 'disney,roi lion,dumbo,toy story4,toy story,le monde de ralph2', 'Vivez une année de rêve avec Disney ...'),
(4, 1, 'Bande annonce Ralph 2.0', 'bande-annonce-ralph-20', '<p></p>\n<p></p><video width=\"300\" height=\"150\"><source src=\"/img/cms/Ralph%202-0%20-%20La%20Bande%20Annonce%20VF.mp4\" type=\"video/mp4\"></source></video><p><span style=\"color:#333333;font-family:Arial, sans-serif;font-size:16px;\">Ralph quitte l’univers des jeux d’arcade pour s’aventurer dans le monde sans limite d’Internet. La Toile va-t-elle résister à son légendaire talent de démolisseur ? Ralph et son amie Vanellope von Schweetz vont prendre tous les risques en s’aventurant dans l’étrange univers d’Internet à la recherche d’une pièce de rechange pour réparer la borne de Sugar Rush, le jeu vidéo dans lequel vit Vanellope. Rapidement dépassés par le monde qui les entoure, ils vont devoir demander de l’aide aux habitants d’Internet, les Netizens, afin de trouver leur chemin, et notamment à Yesss, l’algorithme principal, le cœur et l’âme du site créateur de tendances BuzzzTube</span></p>', '<p>Les héros de nos bambins vous présente la bande annonce de Ralph 2.0 qui sortira le 13 février 2019 en salles !!!! </p>', 'ralph 2.0,disney,dessin animé,pixar,ralph', 'Découvrez la bande annonce de Ralph 2.0 qui sortira en salles le 13 février 2019'),
(4, 2, 'Bande annonce Ralph 2.0', 'bande-annonce-ralph-20', '<p></p><video width=\"300\" height=\"150\"><source src=\"/img/cms/Ralph%202-0%20-%20La%20Bande%20Annonce%20VF.mp4\" type=\"video/mp4\"></source></video><p></p>\n<p><span style=\"color:#333333;font-family:Arial, sans-serif;font-size:16px;\">Ralph quitte l’univers des jeux d’arcade pour s’aventurer dans le monde sans limite d’Internet. La Toile va-t-elle résister à son légendaire talent de démolisseur ? Ralph et son amie Vanellope von Schweetz vont prendre tous les risques en s’aventurant dans l’étrange univers d’Internet à la recherche d’une pièce de rechange pour réparer la borne de Sugar Rush, le jeu vidéo dans lequel vit Vanellope. Rapidement dépassés par le monde qui les entoure, ils vont devoir demander de l’aide aux habitants d’Internet, les Netizens, afin de trouver leur chemin, et notamment à Yesss, l’algorithme principal, le cœur et l’âme du site créateur de tendances BuzzzTube</span></p>', '<p>Les héros de nos bambins vous présente la bande annonce de Ralph 2.0 qui sortira le 13 février 2019 en salles !!!! </p>', 'ralph 2.0,disney,dessin animé,pixar,ralph', 'Découvrez la bande annonce de Ralph 2.0 qui sortira en salles le 13 février 2019'),
(5, 1, 'Bande annonce Dumbo Vf 2019', 'bande-annonce-dumbo-vf-2019', '<p></p>\n<p></p><video width=\"340\" height=\"170\"><source src=\"/img/cms/bande%20annonce%20Dumbo%20-%20Tim%20Burton%20-%20Vf%202019.mp4\" type=\"video/mp4\"></source></video>', '<p><span style=\"color:#333333;font-family:Arial, sans-serif;font-size:16px;\">Dumbo VF 2019</span></p>\n<p></p>\n<p><span style=\"color:#333333;font-family:Arial, sans-serif;font-size:16px;\">Les enfants de Holt Farrier, ex-artiste de cirque chargé de s’occuper d’un éléphanteau dont les oreilles démesurées sont la risée du public, découvrent que ce dernier sait voler</span></p>', 'disney,dumbo,tim burton', 'Les héros de nos bambins sont heureux de vous présenter la bande annonce de Dumbo, le chef d\'oeuvre du mois de février 2019'),
(5, 2, 'Bande annonce Dumbo Vf 2019', 'bande-annonce-dumbo-vf-2019', '<p></p>\n<p></p><video width=\"300\" height=\"150\"><source src=\"/img/cms/dumbo%20avec%20intro.mp4\" type=\"video/mp4\"></source></video>', '<p><span style=\"color:#333333;font-family:Arial, sans-serif;font-size:16px;\">Dumbo VF 2019</span></p>\n<p></p>\n<p><span style=\"color:#333333;font-family:Arial, sans-serif;font-size:16px;\">Les enfants de Holt Farrier, ex-artiste de cirque chargé de s’occuper d’un éléphanteau dont les oreilles démesurées sont la risée du public, découvrent que ce dernier sait voler</span></p>', 'disney,dumbo,tim burton', 'Les héros de nos bambins sont heureux de vous présenter la bande annonce de Dumbo, le chef d\'oeuvre du mois de février 2019'),
(7, 1, 'Bande annonce Lego 2', 'bande-annonce-lego-2', '<p></p><video width=\"300\" height=\"150\"><source src=\"/img/cms/La%20Grande%20Aventure%20Lego%202.mp4\" type=\"video/mp4\"></source></video>', '<p><span style=\"color:#333333;font-family:Arial, sans-serif;font-size:16px;\">Alors que les habitants de Bricksburg coulent des jours heureux depuis cinq ans, une nouvelle et terrible menace se profile à l\'horizon : des envahisseurs Lego Duplo® venus des confins de l\'espace qui détruisent tout sur leur passage !</span><br style=\"color:#333333;font-family:Arial, sans-serif;font-size:16px;\" /><span style=\"color:#333333;font-family:Arial, sans-serif;font-size:16px;\">Pour vaincre ces redoutables ennemis et rétablir la paix dans l\'univers Lego, Emmet, Lucy, Batman et leurs amis devront explorer des mondes lointains et inconnus. Ils découvriront même à cette occasion une étrange galaxie où chaque situation est une comédie musicale ! Cette nouvelle aventure mettra à l\'épreuve leur courage, leur créativité et leurs facultés de Maîtres Constructeurs…</span></p>', 'lego,lego2', 'Découvrez la Bande annonce Lego 2 chez les héros de nos bambins'),
(6, 1, 'Bande annonce Avengers 4 Vf 2019', 'bande-annonce-avengers-4-vf-2019', '<p></p><video width=\"320\" height=\"160\"><source src=\"/img/cms/Avengers%20%20%20Endgame%20-%20Premi%C3%A8re%20bande-annonce%20(VF).mp4\" type=\"video/mp4\"></source></video>', '<p>Avengers : Endgame</p>\n<p>Quatrième volet de la saga Avengers.</p>', 'Avengers,avengers,avengers 4,marvel', 'Découvrez la bande annonce d\'Avengers 4 chez les héros de nos bambins'),
(6, 2, 'Bande annonce Avengers 4 Vf 2019', 'bande-annonce-avengers-4-vf-2019', '<p></p><video width=\"320\" height=\"160\"><source src=\"/img/cms/Avengers%20%20%20Endgame%20-%20Premi%C3%A8re%20bande-annonce%20(VF).mp4\" type=\"video/mp4\"></source></video>', '<p>Avengers : Endgame</p>\n<p>Quatrième volet de la saga Avengers.</p>', 'Avengers,avengers,avengers 4,marvel', 'Découvrez la bande annonce d\'Avengers 4 chez les héros de nos bambins'),
(7, 2, 'Bande annonce Lego 2', 'bande-annonce-lego-2', '<p></p><video width=\"300\" height=\"150\"><source src=\"/img/cms/La%20Grande%20Aventure%20Lego%202.mp4\" type=\"video/mp4\"></source></video>', '<p><span style=\"color:#333333;font-family:Arial, sans-serif;font-size:16px;\">Alors que les habitants de Bricksburg coulent des jours heureux depuis cinq ans, une nouvelle et terrible menace se profile à l\'horizon : des envahisseurs Lego Duplo® venus des confins de l\'espace qui détruisent tout sur leur passage !</span><br style=\"color:#333333;font-family:Arial, sans-serif;font-size:16px;\" /><span style=\"color:#333333;font-family:Arial, sans-serif;font-size:16px;\">Pour vaincre ces redoutables ennemis et rétablir la paix dans l\'univers Lego, Emmet, Lucy, Batman et leurs amis devront explorer des mondes lointains et inconnus. Ils découvriront même à cette occasion une étrange galaxie où chaque situation est une comédie musicale ! Cette nouvelle aventure mettra à l\'épreuve leur courage, leur créativité et leurs facultés de Maîtres Constructeurs…</span></p>', 'lego,lego2', 'Découvrez la Bande annonce Lego 2 chez les héros de nos bambins');
