
-- --------------------------------------------------------

--
-- Structure de la table `vj9e_meta_lang`
--

CREATE TABLE `vj9e_meta_lang` (
  `id_meta` int(10) UNSIGNED NOT NULL,
  `id_shop` int(11) UNSIGNED NOT NULL DEFAULT '1',
  `id_lang` int(10) UNSIGNED NOT NULL,
  `title` varchar(128) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `keywords` varchar(255) DEFAULT NULL,
  `url_rewrite` varchar(254) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `vj9e_meta_lang`
--

INSERT INTO `vj9e_meta_lang` (`id_meta`, `id_shop`, `id_lang`, `title`, `description`, `keywords`, `url_rewrite`) VALUES
(1, 1, 1, '404 error', 'This page cannot be found', '', 'page-not-found'),
(1, 1, 2, 'Erreur 404', 'Impossible de trouver la page', '', 'page-introuvable'),
(2, 1, 1, 'Best sales', 'Our best sales', '', 'best-sales'),
(2, 1, 2, 'Meilleures ventes', 'Nos meilleures ventes', '', 'meilleures-ventes'),
(3, 1, 1, 'Contact us', 'Use our form to contact us', '', 'contact-us'),
(3, 1, 2, 'Contactez-nous', 'Utiliser le formulaire pour nous contacter', '', 'nous-contacter'),
(4, 1, 1, '', 'Shop powered by PrestaShop', '', ''),
(4, 1, 2, 'Les héros de nos bambins - housse de couette, t shirt et chaussette', 'Découvrez notre sélection de housse de couette, de t shirt et chaussette de vos super héros préférés', 'vetement,vetement licence,vetement licence pas cher,reine des neiges ,reine des neiges pas cher,mickey,mickey pas cher,vetement enfant,vetement fille,vetement enfant fille,housse de couette,t shirt,chaussette', ''),
(5, 1, 1, 'Brands', 'Brands list', '', 'brands'),
(5, 1, 2, 'Brands', 'Brands list', '', 'brands'),
(6, 1, 1, 'New products', 'Our new products', '', 'new-products'),
(6, 1, 2, 'Nouveaux produits', 'Nos nouveaux produits', '', 'nouveaux-produits'),
(7, 1, 1, 'Forgot your password', 'Enter the e-mail address you use to sign in to receive an e-mail with a new password', '', 'password-recovery'),
(7, 1, 2, 'Mot de passe oublié', 'Entrez l\'adresse e-mail que vous utilisez pour vous connecter afin de recevoir un e-mail avec un nouveau mot de passe', '', 'recuperation-mot-de-passe'),
(8, 1, 1, 'Prices drop', 'On-sale products', '', 'prices-drop'),
(8, 1, 2, 'Promotions', 'On-sale products', '', 'promotions'),
(9, 1, 1, 'Sitemap', 'Lost ? Find what your are looking for', '', 'sitemap'),
(9, 1, 2, 'sitemap', 'Vous êtes perdu ? Trouvez ce que vous cherchez', '', 'plan du site'),
(10, 1, 1, 'Suppliers', 'Suppliers list', '', 'supplier'),
(10, 1, 2, 'Fournisseurs', 'Liste des fournisseurs', '', 'fournisseur'),
(11, 1, 1, 'Address', '', '', 'address'),
(11, 1, 2, 'Adresse', '', '', 'adresse'),
(12, 1, 1, 'Addresses', '', '', 'addresses'),
(12, 1, 2, 'Adresses', '', '', 'adresses'),
(13, 1, 1, 'Login', '', '', 'login'),
(13, 1, 2, 'Identifiant', '', '', 'connexion'),
(14, 1, 1, 'Cart', '', '', 'cart'),
(14, 1, 2, 'Panier', '', '', 'panier'),
(15, 1, 1, 'Discount', '', '', 'discount'),
(15, 1, 2, 'Remise', '', '', 'reduction'),
(16, 1, 1, 'Order history', '', '', 'order-history'),
(16, 1, 2, 'Historique de vos commandes', '', '', 'historique-commandes'),
(17, 1, 1, 'Identity', '', '', 'identity'),
(17, 1, 2, 'Identité', '', '', 'identite'),
(18, 1, 1, 'My account', '', '', 'my-account'),
(18, 1, 2, 'Mon compte', '', '', 'mon-compte'),
(19, 1, 1, 'Order follow', '', '', 'order-follow'),
(19, 1, 2, 'Suivi de commande', '', '', 'suivi-commande'),
(20, 1, 1, 'Credit slip', '', '', 'credit-slip'),
(20, 1, 2, 'Avoir', '', '', 'avoirs'),
(21, 1, 1, 'Order', '', '', 'order'),
(21, 1, 2, 'Commande', '', '', 'commande'),
(22, 1, 1, 'Search', '', '', 'search'),
(22, 1, 2, 'Rechercher', '', '', 'recherche'),
(23, 1, 1, 'Stores', '', '', 'stores'),
(23, 1, 2, 'Magasins', '', '', 'magasins'),
(24, 1, 1, 'Guest tracking', '', '', 'guest-tracking'),
(24, 1, 2, 'Suivi de commande invité', '', '', 'suivi-commande-invite'),
(25, 1, 1, 'Order confirmation', '', '', 'order-confirmation'),
(25, 1, 2, 'Confirmation de commande', '', '', 'confirmation-commande'),
(34, 1, 1, '', '', '', ''),
(34, 1, 2, '', '', '', ''),
(35, 1, 1, '', '', '', ''),
(35, 1, 2, '', '', '', ''),
(36, 1, 1, '', '', '', ''),
(36, 1, 2, '', '', '', ''),
(37, 1, 1, '', '', '', ''),
(37, 1, 2, '', '', '', ''),
(38, 1, 1, '', '', '', ''),
(38, 1, 2, '', '', '', ''),
(39, 1, 1, '', '', '', ''),
(39, 1, 2, '', '', '', ''),
(40, 1, 1, '', '', '', ''),
(40, 1, 2, '', '', '', ''),
(43, 1, 1, '', '', '', ''),
(43, 1, 2, '', '', '', ''),
(44, 1, 1, '', '', '', ''),
(44, 1, 2, '', '', '', ''),
(45, 1, 1, '', '', '', ''),
(45, 1, 2, '', '', '', ''),
(46, 1, 1, '', '', '', ''),
(46, 1, 2, '', '', '', ''),
(47, 1, 1, '', '', '', ''),
(47, 1, 2, '', '', '', ''),
(48, 1, 1, '', '', '', ''),
(48, 1, 2, '', '', '', ''),
(49, 1, 1, '', '', '', ''),
(49, 1, 2, '', '', '', ''),
(50, 1, 1, '', '', '', ''),
(50, 1, 2, '', '', '', ''),
(51, 1, 1, '', '', '', ''),
(51, 1, 2, '', '', '', ''),
(52, 1, 1, '', '', '', ''),
(52, 1, 2, '', '', '', '');
